spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:postgres}?reWriteBatchedInserts=true
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:password}
    hikari:
      minimum-idle: ${POSTGRES_MIN_IDLE:8}
      maximum-pool-size: ${POSTGRES_MAX_POOL_SIZE:16}
      driver-class-name: org.postgresql.Driver

timebase:
  url: dxtick://${TIMEBASE_HOST:localhost}:${TIMEBASE_PORT:8011}
  batchSize: ${TIMEBASE_BATCH_SIZE:5000}
  streams: ${TIMEBASE_STREAMS_FOR_REPLICATION:orders, four_hours}
  autoDiscovery: ${TIMEBASE_AUTO_DISCOVERY:false}

replicator:
  retryAttempts: ${RETRY_ATTEMPTS:5}

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
    deltix:
      timebase:
        connector: ${APP_LOG_LEVEL:INFO}
